"""domain_expansion_and_remediation"""
"""domain_expansion_and_remediation"""

revision = '8aa4006e3ed0'
down_revision = '20260421_04'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('audit_log_signatures',
    # sa.Column('id', sa.Integer(), nullable=False),
    # ...
    # )
    # op.create_index(op.f('ix_audit_log_signatures_org_id'), 'audit_log_signatures', ['org_id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_org_license_num', 'doctors', ['org_id', 'license_number'], unique=True)
    op.create_index(op.f('ix_doctors_org_id'), 'doctors', ['org_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('patient_number', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('phone_number_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_org_id'), 'patients', ['org_id'], unique=False)
    op.create_index('uq_org_patient_num', 'patients', ['org_id', 'patient_number'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('appointment_number', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_org_appointment_num', 'appointments', ['org_id', 'appointment_number'], unique=True)
    op.create_index(op.f('ix_appointments_org_id'), 'appointments', ['org_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('expense_number', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_org_expense_num', 'expenses', ['org_id', 'expense_number'], unique=True)
    op.create_index(op.f('ix_expenses_org_id'), 'expenses', ['org_id'], unique=False)
    op.create_table('import_batch_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=128), nullable=False),
    sa.Column('record_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.batch_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batch_details_batch_id'), 'import_batch_details', ['batch_id'], unique=False)
    op.create_index(op.f('ix_import_batch_details_org_id'), 'import_batch_details', ['org_id'], unique=False)
    op.create_index(op.f('ix_import_batch_details_record_ref'), 'import_batch_details', ['record_ref'], unique=False)
    # op.drop_index(op.f('ix_audit_log_batch_signatures_org_id'), table_name='audit_log_batch_signatures')
    # op.drop_table('audit_log_batch_signatures')
    op.add_column('attachments', sa.Column('business_owner_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_attachments_business_owner_id'), 'attachments', ['business_owner_id'], unique=False)
    op.create_index(op.f('ix_attachments_org_id'), 'attachments', ['org_id'], unique=False)
    op.create_index(op.f('ix_attachments_sha256'), 'attachments', ['sha256'], unique=False)
    op.create_index(op.f('ix_attachments_uploader_id'), 'attachments', ['uploader_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event'), 'audit_logs', ['event'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_data_validation_issues_batch_id'), 'data_validation_issues', ['batch_id'], unique=False)
    op.create_index(op.f('ix_data_validation_issues_issue_type'), 'data_validation_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_data_validation_issues_org_id'), 'data_validation_issues', ['org_id'], unique=False)
    op.create_index(op.f('ix_data_versions_created_by'), 'data_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_data_versions_entity_id'), 'data_versions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_data_versions_entity_type'), 'data_versions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_data_versions_org_id'), 'data_versions', ['org_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_org_id'), 'export_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_requested_by'), 'export_jobs', ['requested_by'], unique=False)
    # op.drop_constraint(op.f('import_batches_batch_id_key'), 'import_batches', type_='unique')
    # op.create_index(op.f('ix_import_batches_batch_id'), 'import_batches', ['batch_id'], unique=True)
    # op.create_index(op.f('ix_import_batches_org_id'), 'import_batches', ['org_id'], unique=False)
    op.create_index(op.f('ix_metrics_snapshots_org_id'), 'metrics_snapshots', ['org_id'], unique=False)
    op.create_index(op.f('ix_metrics_snapshots_snapshot_date'), 'metrics_snapshots', ['snapshot_date'], unique=False)
    # op.drop_constraint(op.f('organizations_org_code_key'), 'organizations', type_='unique')
    # op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    # op.create_index(op.f('ix_organizations_org_code'), 'organizations', ['org_code'], unique=True)
    op.create_index(op.f('ix_process_definitions_name'), 'process_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_process_definitions_org_id'), 'process_definitions', ['org_id'], unique=False)
    op.create_index(op.f('ix_process_instances_business_id'), 'process_instances', ['business_id'], unique=False)
    op.create_index(op.f('ix_process_instances_idempotency_key'), 'process_instances', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_process_instances_initiator_id'), 'process_instances', ['initiator_id'], unique=False)
    op.create_index(op.f('ix_process_instances_org_id'), 'process_instances', ['org_id'], unique=False)
    op.create_index(op.f('ix_process_instances_process_definition_id'), 'process_instances', ['process_definition_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_action'), 'role_permissions', ['action'], unique=False)
    op.create_index(op.f('ix_role_permissions_resource'), 'role_permissions', ['resource'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_node_key'), 'tasks', ['node_key'], unique=False)
    op.create_index(op.f('ix_tasks_org_id'), 'tasks', ['org_id'], unique=False)
    op.create_index(op.f('ix_tasks_process_instance_id'), 'tasks', ['process_instance_id'], unique=False)
    op.add_column('users', sa.Column('id_card_num_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('phone_number_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('last_failed_login', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    if op.get_bind().dialect.name == 'sqlite':
        op.execute(f"DROP INDEX IF EXISTS {op.f('uq_users_username')}")
    else:
        op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    op.drop_column('users', 'last_failed_login')
    op.drop_column('users', 'phone_number_encrypted')
    op.drop_column('users', 'id_card_num_encrypted')
    op.drop_index(op.f('ix_tasks_process_instance_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_org_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_node_key'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_resource'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_action'), table_name='role_permissions')
    op.drop_index(op.f('ix_process_instances_process_definition_id'), table_name='process_instances')
    op.drop_index(op.f('ix_process_instances_org_id'), table_name='process_instances')
    op.drop_index(op.f('ix_process_instances_initiator_id'), table_name='process_instances')
    op.drop_index(op.f('ix_process_instances_idempotency_key'), table_name='process_instances')
    op.drop_index(op.f('ix_process_instances_business_id'), table_name='process_instances')
    op.drop_index(op.f('ix_process_definitions_org_id'), table_name='process_definitions')
    op.drop_index(op.f('ix_process_definitions_name'), table_name='process_definitions')
    op.drop_index(op.f('ix_organizations_org_code'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_unique_constraint(op.f('organizations_org_code_key'), 'organizations', ['org_code'])
    op.drop_index(op.f('ix_metrics_snapshots_snapshot_date'), table_name='metrics_snapshots')
    op.drop_index(op.f('ix_metrics_snapshots_org_id'), table_name='metrics_snapshots')
    op.drop_index(op.f('ix_import_batches_org_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_batch_id'), table_name='import_batches')
    op.create_unique_constraint(op.f('import_batches_batch_id_key'), 'import_batches', ['batch_id'])
    op.drop_index(op.f('ix_export_jobs_requested_by'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_org_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_data_versions_org_id'), table_name='data_versions')
    op.drop_index(op.f('ix_data_versions_entity_type'), table_name='data_versions')
    op.drop_index(op.f('ix_data_versions_entity_id'), table_name='data_versions')
    op.drop_index(op.f('ix_data_versions_created_by'), table_name='data_versions')
    op.drop_index(op.f('ix_data_validation_issues_org_id'), table_name='data_validation_issues')
    op.drop_index(op.f('ix_data_validation_issues_issue_type'), table_name='data_validation_issues')
    op.drop_index(op.f('ix_data_validation_issues_batch_id'), table_name='data_validation_issues')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event'), table_name='audit_logs')
    op.drop_index(op.f('ix_attachments_uploader_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_sha256'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_org_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_business_owner_id'), table_name='attachments')
    op.drop_column('attachments', 'business_owner_id')
    op.create_table('audit_log_batch_signatures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_log_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('signature', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('audit_log_batch_signatures_org_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_batch_signatures_pkey'))
    )
    op.create_index(op.f('ix_audit_log_batch_signatures_org_id'), 'audit_log_batch_signatures', ['org_id'], unique=False)
    op.drop_index(op.f('ix_import_batch_details_record_ref'), table_name='import_batch_details')
    op.drop_index(op.f('ix_import_batch_details_org_id'), table_name='import_batch_details')
    op.drop_index(op.f('ix_import_batch_details_batch_id'), table_name='import_batch_details')
    op.drop_table('import_batch_details')
    op.drop_index(op.f('ix_expenses_org_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_number'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_appointments_org_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_number'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_patients_patient_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_org_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('doctors')
    op.drop_index('uq_org_license_num', table_name='doctors')
    op.drop_index('uq_org_patient_num', table_name='patients')
    op.drop_index('uq_org_appointment_num', table_name='appointments')
    op.drop_index('uq_org_expense_num', table_name='expenses')
    # op.drop_index(op.f('ix_audit_log_signatures_org_id'), table_name='audit_log_signatures')
    # op.drop_table('audit_log_signatures')
    # ### end Alembic commands ###
